server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jingdongspider?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  level:
#    com.ks.* : debug
